//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriMav.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public Delivery()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int DeliveryId { get; set; }
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public int PersonId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Person Employee { get; set; }
    }
}
