//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriMav.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : Person
    {
        public Employee()
        {
            this.Salaries = new HashSet<Salary>();
        }
    
        public string Code { get; set; }
    
        public virtual ICollection<Salary> Salaries { get; set; }
    }
}
