//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriMav.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice : Transaction
    {
        public Invoice()
        {
            this.Items = new HashSet<InvoiceItem>();
        }
    
        public Shipping Shipping { get; set; }
        public PaymentMethod PaymentMethod { get; set; }
        public string DeliveryAddress { get; set; }
    
        public virtual ICollection<InvoiceItem> Items { get; set; }
    }
}
