//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriMav.Domain
{
    using System;
    
    public enum TransactionType : int
    {
        Invoice = 1,
        Payment = 2,
        CreditNote = 3,
        DebitNote = 4,
        Adjustment = 5
    }
}
