//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriMav.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionPayment
    {
        public int SourceTransactionId { get; set; }
        public int TargetTransactionId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Transaction SourceTransaction { get; set; }
        public virtual Transaction TargetTransaction { get; set; }
    }
}
