//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriMav.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.Reference = new HashSet<Transaction>();
            this.Payments = new HashSet<TransactionPayment>();
        }
    
        public int TransactionId { get; set; }
        public TransactionType TransactionType { get; set; }
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsRefunded { get; set; }
        public decimal Total { get; set; }
        public decimal Balance { get; set; }
        public string Description { get; set; }
        public int FiscalYear { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> ReferenceId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Transaction> Reference { get; set; }
        public virtual ICollection<TransactionPayment> Payments { get; set; }
    }
}
